app:
  name: "Hi! This is Butter!"
  uvicorn_port: 8000
  app_version: "v1"
  api_prefixs:
    app: "/api/v1"
    admin: "/api/admin/v1"
    common: "/api/common/v1"

openai:
  api_key: "b6107211-b6bf-401d-885d-9e30856b8ab9"
  base_url: "https://ark.cn-beijing.volces.com/api/v3"
  model: "ep-20241107153019-pbc5r"
  temperature: 0.38
  max_tokens: 16000
  max_retries: 2

jwt:
  secret_key: "your-secret-key-here"
  algorithm: "HS256"
  access_token_expire_minutes: 30
